DROP TABLE IF EXISTS VEHICULOS;
DROP TABLE IF EXISTS TIPO_LINEA;
DROP TABLE IF EXISTS TIPO_MARCA;

CREATE TABLE TIPO_MARCA(
    ID_MARCA INT(5) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    DESC_MARCA VARCHAR(255) NULL, --No es obligatoria la descripcion
    ACTIVO ENUM("S","N") NOT NULL  -- ¿Activo? "S" = Si, "N" = No
)ENGINE = INNODB;

CREATE TABLE TIPO_LINEA(
    ID_LINEA INT(5) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    DESC_LINEA VARCHAR(255) NULL, --No es obligatoria la descripcion
    ID_MARCA INT(5) UNSIGNED NOT NULL,
    ACTIVO ENUM("S","N") NOT NULL, -- ¿Activo? "S" = Si, "N" = No
    FOREIGN KEY (ID_MARCA) REFERENCES TIPO_MARCA(ID_MARCA)
)ENGINE = INNODB;

CREATE TABLE VEHICULOS(
    NRO_PLACA INT(5) UNSIGNED PRIMARY KEY,
    ID_LINEA INT(5) UNSIGNED NOT NULL,
    MODELO ENUM("2011","2012","2013","2014","2015","2016","2017","2018","2019","2020","2021") NOT NULL,
    FECHA_VEN_SEGURO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL, --NULL porque Pueden existir coches sin seguro en la empresa
    FECHA_VEN_TECNOMECANICA TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL, --NULL porque Pueden existir coches sin tecnomecanica en la empresa
    FECHA_VEN_CONTRATODO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL, --NULL porque Pueden existir coches sin contratodo en la empresa
    FOREIGN KEY (ID_LINEA) REFERENCES TIPO_LINEA(ID_LINEA) 
)ENGINE= INNODB;